port: 9000
target-groups:
  - name: node-server
    algorithm: round-robin
    health-check:
      interval: 3
      timeout: 2
      failure-threshold: 2
      healthy-threshold: 3
      path: "/health"
    targets:
      - host: "localhost"
        port: 8080
      - host: "localhost"
        port: 8081
      - host: "localhost"
        port: 8082
